### ISSUE TITLE
Unauthorised action should not take you to root_url

### ISSUE THREAD

**Issue by pzi** [thefrontiergroup/rails-template#131]
When performing an unauthorised action by going to a specific URL, it should not take the user to `root_url` if there is a referrer url.

This means you don't get transported somewhere entirely different in the app.

**Comment by jordanmaguire** [comment]
It does this currently

```ruby
  def user_not_authorized
    flash[:alert] = "You are not authorized to perform this action."
    redirect_to(request.referrer || root_path)
  end
```

Problem is if you type an invalid URL in it gives you no referer.
