### ISSUE TITLE
Change password form can be submitted without values in inputs

### ISSUE THREAD

**Issue by pzi** [thefrontiergroup/rails-template#155]
Steps to reproduce:

1. Hit Forgot Password link on Sign In form
2. Enter email
3. Hit update password link in email
4. don't enter anything
5. hit submit
6. watch it take you to the user's dashboard

**Comment by jordanmaguire** [comment]
This has been fixed [here](https://github.com/thefrontiergroup/rails-template/commit/2ad25b0eb3b776e1bd58840ff6a1d28ff0e3cff6)
