### ISSUE TITLE
Link to login on 404 page

### ISSUE THREAD

**Issue by pzi** [thefrontiergroup/rails-template#164]
Most of our apps have not much "to offer" when not logged in, so we could add a link to the login page to make it easier for users.

Inspired by Github 404 page on mobile devices:

<image src="https://cloud.githubusercontent.com/assets/2037851/19152015/788be356-8c02-11e6-89f9-603f39c496c9.png" width="320">

**Comment by jordanmaguire** [comment]
That's cos GH 404s when you hit a repo you can't access

Our app handles when you hit a URL you need to be signed in for. When we 404 the page REALLY doesn't exist. Chance of it being because the user is not authenticated is slim.

**Comment by pzi** [comment]
You are right. Nevermind me then :)
