### ISSUE TITLE
Reset password form does not handle errors gracefully when invalid password provided

### ISSUE THREAD

**Issue by jordanmaguire** [thefrontiergroup/rails-template#165]
![screen shot 2016-10-07 at 1 47 17 pm](https://cloud.githubusercontent.com/assets/296341/19179935/93b85fdc-8c94-11e6-9c76-f0867d79dc41.png)

**Comment by jordanmaguire** [comment]
This also happens when the token is outdated

**Comment by pzi** [comment]
Related to https://github.com/thefrontiergroup/rails-template/issues/156
