### ISSUE TITLE
[Feature request] Body class(es) helper

### ISSUE THREAD

**Issue by pzi** [thefrontiergroup/rails-template#46]
I'd like to be able to assign (/add) a custom body class from within
- a view
- a layout

In the past we have dumped a concatenation of controllers as class names, however I'd like not to repeat that, because it might get misused. If people feel like that it would still be good to have the controller names, it could be optional.

Thoughts?

**Comment by jordanmaguire** [comment]
ay @pzi didn't you just implement this feature in another app?

Can you send me the code and I'll bang it in the template?

**Comment by pzi** [comment]
`application_helper.rb`:

```ruby
  def append_body_class(*classes)
    _body_classes.merge(classes)
  end

  # returns the classes that should be on the body as a string
  def get_body_classes
    _body_classes.to_a.join(' ').gsub('/\\/', ' ').gsub(/_/, '-')
  end

  # The internal body classes set
  def _body_classes
    return @_body_classes if @_body_classes
    @_body_classes = Set.new()
    @_body_classes.add('admin') if current_user && current_user.admin?
    @_body_classes
  end
```

In a view:
```haml
- append_body_class("additional-body-class")
```

I will think of some more/different names for the helper to make it more obvious and makes the dev think before he uses it.
