### ISSUE TITLE
Index sort mechanism does work when you have more than on column

### ISSUE THREAD

**Issue by osiro** [thefrontiergroup/rails-template#47]
When you index page has more thank one column, e.g. User name and User role, the sort mechanism seems to fail, other columns will never get sorted.

As far as I can see is something wrong with the `ModelSorter::UriConstructor.new.build_uri_with_cycled_sorting_params` or the view helper `sortable_heading_for`.

![screenshot](https://cloud.githubusercontent.com/assets/97817/9348343/ea177c9c-4667-11e5-8fe5-62147af63e60.gif)

**Comment by jordanmaguire** [comment]
Yeah - you're right. I'll look at that now.

**Comment by jordanmaguire** [comment]
Fixed by https://github.com/thefrontiergroup/rails-template/pull/49

**Comment by pzi** [comment]
No need for extra comment, Github will store the reference automagically for you when you reference it in your PR and it gets merged:

![](http://puu.sh/jGJWq/5a48281053.png)

**Comment by pzi** [comment]
Fyi: https://help.github.com/articles/closing-issues-via-commit-messages/
