### ISSUE TITLE
Blocks & options for page_navigation_helper

### ISSUE THREAD

**Issue by pzi** [thefrontiergroup/rails-template#69]
Would be nice if the `page_navigation_helper` would accept some form of `html_options` and a block.

The thing is the helper itself returns a `li` with an `a` nested in it. So we would need a way of telling it where to apply the `html_options` and `block` (`li` or `a`)?

Or should we just resort to another method when the need arises to create anything else than just a list of basic links?

Example:
```haml
%ul.user-nav.nav
  = page_navigation_link_to "My Activities ", volunteer_activities_path
  %li
    = link_to "#" do
      %span.badge-notification
        %span 3
      Requirements
  %li
    = link_to "#" do
      %span.badge-notification
        %span 1
      Feedback
  %li= link_to "Inductions", "#"
  %li
    = link_to "#" do
      %span.badge-notification
        %span 15
      Reminders
```

The above example would add an extra class to the `li` and a block into the link.

Thoughts?

**Comment by osiro** [comment]
Go nuts!

Only bring benefits imo.

**Comment by pzi** [comment]
Not sure how to solve this problem. Because

1) #91 will remove that helper and
2) [active_link_to](https://github.com/comfy/active_link_to) doesn't accept a `block` either.

Will probably have to be a custom helper for these cases? Thoughts?

**Comment by jordanmaguire** [comment]
active_link_to does accept a block. This is sorted!
