### ISSUE TITLE
page_navigation_helper needs to handle subpages

### ISSUE THREAD

**Issue by pzi** [thefrontiergroup/rails-template#70]
When on a page with subpages/-views like

* `.../events/1/`
* `.../events/1/team`
* `.../events/1/updates`

Both tab links are *active*.

![screen shot 2015-12-04 at 14 30 18](https://cloud.githubusercontent.com/assets/2037851/11583336/9e4b2324-9a93-11e5-9319-7407c67efdf1.png)

I suppose there should be some flag to toggle if I want to include parent or not? Better idea?

**Comment by osiro** [comment]
Actually... `page_navigation_helper` needs to be refactored.

It does not work for subpages and request referrers either.

Example:

1. User click on tab "Send message"
2. User fill in the for in "Send message" page with invalid data
3. controller `Message::create` renders `new` action

Results: current path "/send_message", expected path "/send_message/new".

```ruby
"/send_message".include?("/send_message/new")
=> false
```

Suggested implementation:

**Comment by pzi** [comment]
Maybe we could use https://github.com/comfy/active_link_to ?

**Comment by osiro** [comment]
Suggested implementation:

```ruby
module PageNavigationHelper

  def page_navigation_link_to(title, path, tab_id=nil)
    args = {}

    args = {class: "active"} if tab_id.present? && request.url.include?("tab_id=#{tab_id}")
    content_tag(:li, args) do
      link_to(title, path)
    end
  end
end
```

```ruby
require 'rails_helper'

describe PageNavigationHelper do
  describe "#page_navigation_link_to" do
    subject { helper.page_navigation_link_to(title, path, tab_id) }
    let(:title) { "Users" }
    let(:current_path)  { "/hello/world?" }
    let(:path)  { "/go/to/users" }
    let(:tab_id) { :tab_1 }

    before do
      request_double = double
      allow(helper).to receive(:request).and_return(request_double)
      allow(request_double).to receive(:url).and_return(current_path)
    end

    context "when tab_id matches with tab_id of the current path" do
      before { current_path << "?tab_id=#{tab_id}" }
      it { should eq("<li class=\"active\"><a href=\"/go/to/users\">Users</a></li>") }
    end

    context "when tab_id does not match with tab_id of the current path" do
      before { current_path << "?tab_id=lalala" }
      it { should eq("<li><a href=\"/go/to/users\">Users</a></li>") }
    end

    context "when tab_id is nil" do
      let(:tab_id) { nil }
      it { should eq("<li><a href=\"/go/to/users\">Users</a></li>") }
    end
  end
end
```

I run out of time to PR RT and fix broken tests this change will cause, can someone else address to this issue?

**Comment by osiro** [comment]
@pzi feel free to play with active_link_to, it looks interesting.

**Comment by pzi** [comment]
Both take5 feedback and temp are using it. Not sure if it was added somewhere else too.
