### ISSUE TITLE
button_to generates form which occupies entire line

### ISSUE THREAD

**Issue by jgunnink** [thefrontiergroup/rails-template#77]
`button_to` creates a form which is a block level element, it should be setup to be inline-block so it can be used inline.

**Comment by pzi** [comment]
It's the default behaviour for HTML `<form>` elements.
If we need the form to be inline in certain cases, we could use a helper class like so:

`= button_to "New", { action: "new" }, form_class: "form-inline"`.

I am unsure whether rails-template should cater for that or not. Maybe at some point we can add that helper class, but I am not a big fan of using `button_to` generally. We can add support per project if required?

**Comment by jordanmaguire** [comment]
Yeah this is not a Rails template issue. `button_to` isn't even used in RT.
